### ISSUE TITLE
getDefaultProfileName side effects

### ISSUE THREAD

**Issue by scottned** [planttheidea/moize#176] opened 2022-08-12 18:16 UTC
The `getDefaultProfileName` call that is made when a name is not passed to the moize constructor was consistently triggering out of memory errors in an app I'm working on.  Digging into the problem, I discovered that the `new Error().stack` [call](https://github.com/planttheidea/moize/blob/6ae4576f492cd78b5dac4fcc9910e0bd63705563/src/stats.ts#L95) inside that method has a bunch of non-obvious side effects.  The most significant is fetching, parsing and sorting the source map related to the caller.  Something about doing that in a dev environment was trigging OOM (possibly due to reloads).  For reference, the particular source map for our bundled app is about 14mb.

Of course, the easy solution is to just pass a `profileName` in the [options](https://www.npmjs.com/package/moize#profilename) for the constructor.  However, it might be a good idea to mention this in the docs which are a bit misleading when they say "You must be collecting statistics for this option to take effect."  That is, there is definitely an effect of passing this option even if stats are not collected.

**Comment by planttheidea** [comment] 2022-08-19 22:41
This is definitely unexpected, since stack traces historically have referenced the "raw" code. There are even [questions on an ES proposal on the topic] (https://github.com/tc39/proposal-error-stacks/issues/19) that call this out. That said, the use of the stack was to try to provide some context about location of an anonymous function, and the cost you describe is much too high for such a small benefit. I can update to remove this usage.

As to the documentation call-out, this side effect was intended (it should have had no effect), however the wording is a bit vague. I can update to clarify that providing a `profileName` will only provide value when collecting stats.

**Comment by planttheidea** [comment] 2022-08-20 23:00
@scottned - simple PR created to remove the use of the stack for profile name derivation. I'll let it simmer for a bit, both so that I can review my work with a fresh set of eyes, but also for you to weigh in on it (for example, the fact I'm not considering this a breaking change). If you don't provide feedback within a few days I'll merge away because of the serious potential consequences as-is.

**Comment by planttheidea** [comment] 2022-08-24 15:12
This should be fixed as-of `6.1.2`. If you have any more issues, let me know!

**Closed by planttheidea** 2022-08-24 15:12 UTC
Labels: bug
